export const blogData = [
  {
    slug: 'hello-world',
    title: 'Hello World — Why I am trying to start blogging',
    date: '2026-03-01',
    summary:
      'I have been building things for years but almost never writing them down. This is me fixing that.',
    tags: ['blogging'],
  },
]

export const userData = {
  name: 'Teng Fone',
  linkedin: 'https://www.linkedin.com/in/tengfonephang/',
  medium: 'https://medium.com/@tengfone',
  github: 'https://github.com/tengfone',
  buymeacoffee: 'https://www.buymeacoffee.com/tengfone',
  formBold: 'https://formbold.com/s/3ZdJ6',
  projects: [
    {
      title: 'Retrava',
      desc: 'Forgot to track your run? Draw your route, set your pace, and export a TCX file. Compatible with Strava, Garmin, and all major fitness platforms.',
      link: 'https://retrava.vercel.app/',
      image: 'https://retrava.vercel.app/animation.gif',
      tech: ['NextJS', 'Tailwind'],
    },
    {
      title: 'ForgeTools',
      desc: 'Comprehensive offline desktop application built with Electron that provides a suite of essential development tools for software engineers.',
      link: 'https://github.com/tengfone/forgetools',
      image: 'https://github.com/tengfone/forgetools/raw/main/assets/demo.gif',
      tech: ['Electron', 'CI/CD'],
    },
    {
      title: 'DeadText',
      desc: 'A Telegram text-based zombie survival game. It presents a unique scenario generated by a LLM (mistralai/mistral-nemo). Players make decisions to survive a zombie apocalypse, facing random events and challenges.',
      link: 'https://github.com/tengfone/deadtext',
      image:
        'https://github.com/tengfone/deadtext/blob/main/assets/demo.gif?raw=true',
      tech: ['Prompting'],
    },
    {
      title: 'Chat-Kaki',
      desc: 'An educational piece of a conversational bot. Removed demo due to costing.',
      link: 'https://github.com/tengfone/chat-kaki',
      image:
        'https://github.com/tengfone/chat-kaki/blob/main/demo_chatkaki.gif?raw=true',
      tech: ['NextJS', 'Pinecone', 'Langchain', 'Stripe'],
    },
    {
      title: 'Yestion',
      desc: 'A Notion Copy to test out the latest UI frameworks',
      link: 'https://yestion-one.vercel.app/',
      image:
        'https://github.com/tengfone/yestion/blob/main/demo_yestion.gif?raw=true',
      tech: ['NextJS', 'Tailwind'],
    },
    {
      title: 'OpenRiver',
      desc: 'Ethereum smart contracts specifically designed for buying and selling unique digital assets.',
      link: 'https://open-river.vercel.app/',
      image: 'https://j.gifs.com/288o0W.gif',
      tech: ['React', 'Solidity', 'Ethereum'],
    },
    {
      title: 'Browser-o-matic',
      desc: 'A Browser Prompter running on Electron co-created by AI',
      link: 'https://github.com/tengfone/browser-o-matic',
      image: 'https://github.com/tengfone/browser-o-matic/raw/master/demo.gif',
      tech: ['Electron', 'Claude', 'ProductivityAI'],
    },
    {
      title: 'Deep Learning: HandWash',
      desc: 'Due to COVID-19, this handwashing project utilizes deep learning to detect and advise users on how to wash their hands.',
      link: 'https://handwashdl.herokuapp.com/',
      image:
        'https://github.com/tengfone/handwashStreamLit/blob/main/streamlit.png?raw=true',
      tech: ['AlexNet', 'Streamlit', 'PyTorch'],
    },
    {
      title: 'Big Data Book Review',
      desc: 'A fullstack web application that allows users to review books and their ratings.',
      link: 'https://github.com/tengfone/AmaNerdBookReview',
      image:
        'https://github.com/tengfone/AmaNerdBookReview/blob/master/screenshots/splashpage.PNG?raw=true',
      tech: ['AWS', 'React', 'Hadoop', 'Spark'],
    },
    {
      title: 'Green Scanner',
      desc: "Grand Championship for Hack Junction X Asia 2020's Hackathon.",
      link: 'https://github.com/tengfone/green_scanner_flutter',
      image:
        'https://github.com/tengfone/green_scanner_flutter/blob/master/screenshots/login.jpg?raw=true',
      tech: ['Flutter', 'Hackathon'],
    },
    {
      title: 'URL Shortener',
      desc: 'A URL shortener that allows users to shorten their long URLs.',
      link: 'https://tf-urlshortener.vercel.app/',
      image:
        'https://github.com/tengfone/urlshortener/blob/main/screenshots/demo.gif?raw=true',
      tech: ['AWS', 'MySQL', 'React'],
    },
    {
      title: 'And More',
      desc: '...',
      link: 'https://github.com/tengfone?tab=repositories',
      image:
        'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png',
      tech: [''],
    },
  ],
  experience: [
    {
      title: 'AI Platform / Full Stack Data Engineer',
      company: 'GovTech Singapore',
      year: '2021 to Present',
      subSections: [
        {
          title: 'AI Platform and LLM Infrastructure',
          desc: 'Built an end-to-end AI platform on Kubernetes, owning the frontend, Go orchestration layer, APIs, and observability needed to standardize access to internal and external AI services. Implemented governance controls including SSO, RBAC, audit logging, and secrets-managed integrations, and supported hardening for restricted environments through MFA, network controls, and VAPT remediation.',
        },
        {
          title: 'Data Privacy and Cloud Foundations',
          desc: 'Developed a cloud-based data privacy platform for large-scale clinical datasets, enabling secure policy analysis while improving platform efficiency and reducing AWS costs by about 30%. Supported national-level health economics work by building scalable data engineering pipelines for sensitive healthcare data.',
        },
        {
          title: 'Leadership and Adoption',
          desc: 'Partnered with teams to cut AI proof-of-concept delivery time by 75% through reusable MLOps pipelines and rapid LLM prototyping. Raised engineering quality through structured peer review, practical AI-assisted development patterns, and internal community building such as AI Wednesday.',
          link: { label: 'AI Wednesday', href: 'https://lorong.ai/' },
        },
      ],
      highlights: [
        'Rolled out a multi-tenant MLOps platform across AWS and Azure for 450+ users across 90+ teams, standardizing governed model development and deployment, including RAG workflows.',
        'Built and scaled an enterprise LLM gateway serving millions of monthly requests across commercial providers and self-hosted inference, improving cost, latency, and vendor flexibility.',
        'Reduced AI proof-of-concept delivery time by 75% through reusable MLOps pipelines and rapid prototyping with stakeholders.',
        'Built privacy-preserving data platforms for sensitive clinical workloads, reducing AWS costs by about 30% while enabling secure large-scale analysis in both cloud and restricted environments.',
      ],
    },
    {
      title: 'Volunteer — Python Instructor',
      company: 'Code In The Community',
      year: '2022',
      desc: 'Volunteer Python Instructor at CITC, teaching beginner Python, simple electronics and coding projects to underprivileged children.',
    },
    {
      title: "Bachelor's Degree",
      company: 'Singapore University of Technology and Design (SUTD)',
      year: '2021',
      desc: 'BSc Computer Science Design, Minor in Artificial Intelligence and Humanities. SUTD Undergraduate Merit Scholarship.',
    },
    {
      title: 'Co Founder',
      company: 'Swifty',
      year: '2021',
      desc: [
        'Built and shipped a full-stack e-commerce platform using React and AWS and GCP',
        'Owned delivery from MVP to deployment and iteration',
      ],
    },
    {
      title: 'NLP Research Intern',
      company: 'DeCLaRe Lab @ SUTD',
      year: '2020',
      desc: [
        'Worked on complex question answering using Transformer models',
        'Benchmarked baselines such as BERT and ELMo',
      ],
    },
    {
      title: 'Data Analyst Intern',
      company: 'Univac',
      year: '2019',
      desc: [
        `Built Python ETL pipelines \n Streamed shop floor metrics via Kafka and NodeJS to surface near real-time insights`,
      ],
    },
    {
      title: 'Diploma In Mechanical Engineering',
      company: 'Singapore Polytechnic',
      year: '2015',
      desc: 'Graduated with a Diploma With Merit',
    },
  ],
}
