export const userData = {
  name: 'Teng Fone',
  linkedin: 'https://www.linkedin.com/in/tengfonephang/',
  medium: 'https://medium.com/@tengfone',
  github: 'https://github.com/tengfone',
  formBold: 'https://formbold.com/s/3ZdJ6',
  projects: [
    {
      title: 'ForgeTools',
      desc: 'Comprehensive offline desktop application built with Electron that provides a suite of essential development tools for software engineers.',
      link: 'https://github.com/tengfone/forgetools',
      image:
        'https://github.com/tengfone/forgetools/raw/main/assets/demo.gif',
      tech: ['Electron', 'CI/CD'],
    },
    {
      title: 'DeadText',
      desc: 'A Telegram text-based zombie survival game. It presents a unique scenario generated by a LLM (mistralai/mistral-nemo). Players make decisions to survive a zombie apocalypse, facing random events and challenges.',
      link: 'https://github.com/tengfone/deadtext',
      image:
        'https://github.com/tengfone/deadtext/blob/main/assets/demo.gif?raw=true',
      tech: ['Prompting'],
    },
    {
      title: 'Chat-Kaki',
      desc: 'An educational piece of a conversational bot. Removed demo due to costing.',
      link: 'https://github.com/tengfone/chat-kaki',
      image:
        'https://github.com/tengfone/chat-kaki/blob/main/demo_chatkaki.gif?raw=true',
      tech: ['NextJS', 'Pinecone', 'Langchain', 'Stripe'],
    },
    {
      title: 'Yestion',
      desc: 'A Notion Copy to test out the latest UI frameworks',
      link: 'https://yestion-one.vercel.app/',
      image:
        'https://github.com/tengfone/yestion/blob/main/demo_yestion.gif?raw=true',
      tech: ['NextJS', 'Tailwind'],
    },
    {
      title: 'OpenRiver',
      desc: 'Ethereum smart contracts specifically designed for buying and selling unique digital assets.',
      link: 'https://open-river.vercel.app/',
      image: 'https://j.gifs.com/288o0W.gif',
      tech: ['React', 'Solidity', 'Ethereum'],
    },
    {
      title: 'Browser-o-matic',
      desc: 'A Browser Prompter running on Electron co-created by AI',
      link: 'https://github.com/tengfone/browser-o-matic',
      image: 'https://github.com/tengfone/browser-o-matic/raw/master/demo.gif',
      tech: ['Electron', 'Claude', 'ProductivityAI'],
    },
    {
      title: 'Deep Learning: HandWash',
      desc: 'Due to COVID-19, this handwashing project utilizes deep learning to detect and advise users on how to wash their hands.',
      link: 'https://handwashdl.herokuapp.com/',
      image:
        'https://github.com/tengfone/handwashStreamLit/blob/main/streamlit.png?raw=true',
      tech: ['AlexNet', 'Streamlit', 'PyTorch'],
    },
    {
      title: 'Big Data Book Review',
      desc: 'A fullstack web application that allows users to review books and their ratings.',
      link: 'https://github.com/tengfone/AmaNerdBookReview',
      image:
        'https://github.com/tengfone/AmaNerdBookReview/blob/master/screenshots/splashpage.PNG?raw=true',
      tech: ['AWS', 'React', 'Hadoop', 'Spark'],
    },
    {
      title: 'Green Scanner',
      desc: "Grand Championship for Hack Junction X Asia 2020's Hackathon.",
      link: 'https://github.com/tengfone/green_scanner_flutter',
      image:
        'https://github.com/tengfone/green_scanner_flutter/blob/master/screenshots/login.jpg?raw=true',
      tech: ['Flutter', 'Hackathon'],
    },
    {
      title: 'URL Shortener',
      desc: 'A URL shortener that allows users to shorten their long URLs.',
      link: 'https://tf-urlshortener.vercel.app/',
      image:
        'https://github.com/tengfone/urlshortener/blob/main/screenshots/demo.gif?raw=true',
      tech: ['AWS', 'MySQL', 'React'],
    },
    {
      title: 'And More',
      desc: '...',
      link: 'https://github.com/tengfone?tab=repositories',
      image:
        'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png',
      tech: [''],
    },
  ],
  experience: [
    {
      title: 'Data Engineer',
      company: 'GovTech',
      year: '2021-2025',
      desc: "Technology Associate Programme (TAP), an exclusive two-year leadership-trainee initiative, I honed my technical and professional skills within the Data Science and Artificial Intelligence Department (DSAID). My role encompassed the development of a cloud-based data privacy platform, leveraging React, Terraform, and AWS to enhance performance and security. I optimized cloud resource allocation on AWS, significantly reducing operational costs, while also designing and managing CI/CD pipelines using GitLab to streamline development workflows. In addition to maintaining on-premise analytics platforms, I contributed to data strategy planning and capability development at the Whole-of-Government (WOG) level. I led the implementation of cloud infrastructure for MLOps/AIOps, driving AI innovation across 30 government agencies and serving over 450 users. My multi-cloud approach, utilizing AWS and Azure, resulted in substantial cost savings. I played a pivotal role in spearheading Whole-of-Government GenAI adoption, which reduced time-to-market by 75% and enhanced productivity. Throughout my tenure, I supervised junior engineers, introduced structured code reviews, and advanced software engineering practices within the team. I also organized training workshops and led a hackathon that identified high-potential projects for future growth. My contributions extended to Singapore's National AI 2.0 Strategy, where I hosted AI events and fostered AI community building and innovation for the nation."
    },
    {
      title: 'Volunteer - Python Instructor',
      company: 'Code In The Community',
      year: '2022',
      desc: 'Code in the Community (CITC) is Singapore’s largest free coding programme for kids from disadvantaged backgrounds.',
    },
    {
      title: 'Graduate Degree',
      company: 'Singapore University of Technology and Design',
      year: '2021',
      desc: 'Graduated with a degree in Computer Science with minors in A.I and Humanities',
    },
    {
      title: 'Co-Founder',
      company: 'SwiftySG',
      year: '2020',
      desc: 'A start up that aims to bridge local business to daily consumers via digitalization by developing a full stack web application (AWS/SEO ReactJS) for the digitalization process',
    },
    {
      title: 'NLP Research Intern',
      company: 'DeCLaRe Lab',
      year: '2020',
      desc: 'Researched on Complex Question Answering using Transformers Library (Python)',
    },
    {
      title: 'Android Developer',
      company: 'SUTD',
      year: '2019',
      desc: "Developed an Android app using native language (JAVA) to provide a platform users to request and offer goods & services. Main features include flexible pricing and wide variety of goods and services whilst ensuring user's safety through a log-in system as well as using Telegram / in-app chat as mode of communication to prevent disclosing of phone numbers. Developed with MVP design pattern in mind and used VCS internally with a team of 6, developed using Google's back end services such as Firebase. Awarded grant by Mitsubishi Corp to continue for further development.",
    },
    {
      title: 'Data Analyst Intern',
      company: 'The Univac Group',
      year: '2019',
      desc: 'ETL Apache Kafka Streaming data coupled with scripts and collaborating with a team of engineers to filter out meaningful data (Python, OpenFaas, Docker, MicrosoftSQL, PyTest - Python Script Testing). Developed a Microsoft Team Bots for machine down time (Python). Utilized Microsoft PowerBI and Microstrategy for visual data interpretation (Javascript, D3 Visuals)',
    },
    {
      title: 'Diploma In Mechanical Engineering',
      company: 'Singapore Polytechnic',
      year: '2015',
      desc: 'Graduated with a Diploma With Merit, offered a scholarship to SUTD',
    },
    {
      title: 'Project Intern',
      company: 'Avantek PTE LTD',
      year: '2015',
      desc: 'Designed and fabricated fixture for stamping machine to streamline production process.',
    },
    {
      title: 'Internship',
      company: 'Pratt & Whitney',
      year: '2014',
      desc: 'Internship at Pratt & Whitney Customer Training Center (Beijing) primarily dealing with material science and fluid dynamic of jet engines.',
    },
  ],
}
