export const blogData = [
  {
    slug: 'agentic-mlops-review-flow-april-2026',
    title:
      'What Building an Agentic MLOps Review Flow in an Isolated Environment Taught Me',
    date: '2026-04-05',
    summary:
      'After building a ReAct-style model promotion review system for HDB resale price prediction, the hardest part was not adding the agent — it was making it trustworthy in an isolated enterprise environment where bad decisions have real business cost.',
    tags: ['MLOps', 'AI', 'LangGraph', 'agentic', 'machine-learning'],
  },
  {
    slug: 'ai-coding-assistants-value-workflow-march-2026',
    title: 'AI Coding Assistants: Value, Workflow, and Tradeoffs (March 2026)',
    date: '2026-03-04',
    summary:
      'A workflow-first take on AI coding tools: what feels like good value, what I would pick depending on your constraints, and why PLAN/EXECUTE beats one-model-does-everything.',
    tags: ['AI', 'tooling', 'productivity', 'coding'],
  },
  {
    slug: 'hello-world',
    title: 'Hello World — Why I am trying to start blogging',
    date: '2026-03-01',
    summary:
      'I have been building things for years but almost never writing them down. This is me fixing that.',
    tags: ['blogging'],
  },
]

export const userData = {
  name: 'Teng Fone',
  linkedin: 'https://www.linkedin.com/in/tengfonephang/',
  medium: 'https://medium.com/@tengfone',
  github: 'https://github.com/tengfone',
  buymeacoffee: 'https://www.buymeacoffee.com/tengfone',
  formBold: 'https://formbold.com/s/3ZdJ6',
  projects: [
    {
      title: 'PrivatePixel',
      desc: 'A local-first browser image utility suite for resizing, compressing, converting, cropping, editing metadata, and removing backgrounds without uploads or remote inference.',
      link: 'https://tengfone.github.io/privatepixel/',
      image:
        'https://raw.githubusercontent.com/tengfone/privatepixel/main/public/assets/privatepixel.gif',
      tech: ['Vite', 'React', 'TypeScript', 'Web Workers', 'WASM'],
    },
    {
      title: 'Retrava',
      desc: 'Forgot to track your run? Draw your route, set your pace, and export a TCX file. Compatible with Strava, Garmin, and all major fitness platforms.',
      link: 'https://retrava.vercel.app/',
      image: 'https://retrava.vercel.app/animation.gif',
      tech: ['NextJS', 'Tailwind'],
    },
    {
      title: 'ForgeTools',
      desc: 'Comprehensive offline desktop application built with Electron that provides a suite of essential development tools for software engineers.',
      link: 'https://github.com/tengfone/forgetools',
      image: 'https://github.com/tengfone/forgetools/raw/main/assets/demo.gif',
      tech: ['Electron', 'CI/CD'],
    },
    {
      title: 'MemeOps',
      desc: 'A static JSON API and docs site for infra humor, AI agent satire, and postmortem-grade truth, with versioned endpoints and generated API catalogs.',
      link: 'https://tengfone.github.io/memeops/',
      image:
        'https://raw.githubusercontent.com/tengfone/memeops/main/memeops.gif',
      tech: ['Static API', 'GitHub Pages', 'Node.js', 'JSON'],
    },
    {
      title: 'GovAgent Panic',
      desc: 'A real-time canvas arcade defense game about surviving five workdays inside a chaotic government AI platform office while incidents and audits pile up.',
      link: 'https://tengfone.github.io/GovAgentPanic/',
      image:
        'https://raw.githubusercontent.com/tengfone/GovAgentPanic/main/assets/govagent.gif',
      tech: ['Canvas', 'JavaScript', 'Game', 'GitHub Pages'],
    },
    {
      title: 'DeadText',
      desc: 'A Telegram text-based zombie survival game. It presents a unique scenario generated by a LLM (mistralai/mistral-nemo). Players make decisions to survive a zombie apocalypse, facing random events and challenges.',
      link: 'https://github.com/tengfone/deadtext',
      image:
        'https://github.com/tengfone/deadtext/blob/main/assets/demo.gif?raw=true',
      tech: ['Prompting'],
    },
    {
      title: 'Chat-Kaki',
      desc: 'An educational piece of a conversational bot. Removed demo due to costing.',
      link: 'https://github.com/tengfone/chat-kaki',
      image:
        'https://github.com/tengfone/chat-kaki/blob/main/demo_chatkaki.gif?raw=true',
      tech: ['NextJS', 'Pinecone', 'Langchain', 'Stripe'],
    },
    {
      title: 'Yestion',
      desc: 'A Notion Copy to test out the latest UI frameworks',
      link: 'https://yestion-one.vercel.app/',
      image:
        'https://github.com/tengfone/yestion/blob/main/demo_yestion.gif?raw=true',
      tech: ['NextJS', 'Tailwind'],
    },
    {
      title: 'OpenRiver',
      desc: 'Ethereum smart contracts specifically designed for buying and selling unique digital assets.',
      link: 'https://open-river.vercel.app/',
      image: 'https://j.gifs.com/288o0W.gif',
      tech: ['React', 'Solidity', 'Ethereum'],
    },
    {
      title: 'Browser-o-matic',
      desc: 'A Browser Prompter running on Electron co-created by AI',
      link: 'https://github.com/tengfone/browser-o-matic',
      image: 'https://github.com/tengfone/browser-o-matic/raw/master/demo.gif',
      tech: ['Electron', 'Claude', 'ProductivityAI'],
    },
    {
      title: 'Deep Learning: HandWash',
      desc: 'Due to COVID-19, this handwashing project utilizes deep learning to detect and advise users on how to wash their hands.',
      link: 'https://handwashdl.herokuapp.com/',
      image:
        'https://github.com/tengfone/handwashStreamLit/blob/main/streamlit.png?raw=true',
      tech: ['AlexNet', 'Streamlit', 'PyTorch'],
    },
    {
      title: 'Big Data Book Review',
      desc: 'A fullstack web application that allows users to review books and their ratings.',
      link: 'https://github.com/tengfone/AmaNerdBookReview',
      image:
        'https://github.com/tengfone/AmaNerdBookReview/blob/master/screenshots/splashpage.PNG?raw=true',
      tech: ['AWS', 'React', 'Hadoop', 'Spark'],
    },
    {
      title: 'Green Scanner',
      desc: "Grand Championship for Hack Junction X Asia 2020's Hackathon.",
      link: 'https://github.com/tengfone/green_scanner_flutter',
      image:
        'https://github.com/tengfone/green_scanner_flutter/blob/master/screenshots/login.jpg?raw=true',
      tech: ['Flutter', 'Hackathon'],
    },
    {
      title: 'URL Shortener',
      desc: 'A URL shortener that allows users to shorten their long URLs.',
      link: 'https://tf-urlshortener.vercel.app/',
      image:
        'https://github.com/tengfone/urlshortener/blob/main/screenshots/demo.gif?raw=true',
      tech: ['AWS', 'MySQL', 'React'],
    },
    {
      title: 'And More',
      desc: '...',
      link: 'https://github.com/tengfone?tab=repositories',
      image:
        'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png',
      tech: [''],
    },
  ],
  experience: [
    {
      // `title` is the official GovTech job title, deliberately kept separate from the
      // AI Platform Engineer identity on the homepage. Promotion to Senior Data Engineer
      // is effective Oct 2026; when it lands, split this into a two-role header
      // (Senior Data Engineer 2026 to Present / Data Engineer 2021 to 2026).
      title: 'Data Engineer — AI Platform Engineering',
      company: 'GovTech Singapore',
      year: 'Sep 2021 to Present',
      desc: 'I work with customer teams and product stakeholders to turn AI use cases into shared production capabilities. Across these platforms, I build authentication, RBAC, audit logging and secrets management, and help resolve production incidents in enterprise and restricted environments.',
      subSections: [
        {
          title: 'MLOps & AI API Platform',
          role: 'Technical Owner',
          desc: 'Led engineering of a multi-tenant platform across AWS and Azure, shaping architecture and roadmap decisions with product stakeholders.',
          bullets: [
            'Enabled governed model development and deployment for 450+ users across 90+ teams.',
            'Partnered with customer teams to cut POC delivery time by 75%, with reusable RAG reference implementations and OpenAI-compatible APIs.',
            'Scaled shared AI API infrastructure to millions of requests/month, routing across commercial providers and self-hosted models using vLLM.',
          ],
        },
        {
          title: 'Whole-of-Government AI Platform',
          role: 'Core Full-Stack Engineer',
          desc: 'Own React applications, Go microservices and APIs, authentication, usage analytics and observability on Kubernetes.',
          bullets: [
            'Productionized the platform to reliably serve more than 3,000 requests/minute across governed AI capabilities.',
          ],
        },
        {
          title: 'Self-Hosted GenAI Platform',
          role: 'Engineering Delivery Lead',
          desc: 'Led the successful migration into a highly restricted environment, coordinating engineering delivery, stakeholders and operational readiness.',
          bullets: [
            'Now coordinate newer-model onboarding, inference scaling, routing and model lifecycle management, aligning priorities across product and technical leads.',
          ],
        },
      ],
      earlier: [
        {
          title: 'Usage Analytics & Cost Governance',
          desc: 'Built Python/PySpark pipelines processing millions of logs/day to support usage reporting, quotas, budgeting and cost recovery.',
        },
        {
          title: 'Secure Clinical Data Platforms',
          desc: 'Built and operated secure platforms for large-scale clinical datasets using Python/PySpark, AWS, Terraform and CI/CD, enabling national-level health economics analysis while reducing cloud costs by approximately 30%.',
        },
        {
          title: 'Engineering Enablement',
          desc: 'Mentor interns and junior engineers, introduced structured peer review, and co-founded AI Wednesday to share practical AI/MLOps approaches.',
          link: { label: 'AI Wednesday', href: 'https://lorong.ai/' },
        },
      ],
    },
    {
      title: 'Volunteer — Python Instructor',
      company: 'Code In The Community',
      year: '2022',
      desc: 'Volunteer Python Instructor at CITC, teaching beginner Python, simple electronics and coding projects to underprivileged children.',
    },
    {
      title: "Bachelor's Degree",
      company: 'Singapore University of Technology and Design (SUTD)',
      year: '2021',
      desc: 'BSc Computer Science Design, Minor in Artificial Intelligence and Humanities. SUTD Undergraduate Merit Scholarship.',
    },
    {
      title: 'Co Founder',
      company: 'Swifty',
      year: '2021',
      desc: [
        'Built and shipped a full-stack e-commerce platform using React and AWS and GCP',
        'Owned delivery from MVP to deployment and iteration',
      ],
    },
    {
      title: 'NLP Research Intern',
      company: 'DeCLaRe Lab @ SUTD',
      year: '2020',
      desc: [
        'Worked on complex question answering using Transformer models',
        'Benchmarked baselines such as BERT and ELMo',
      ],
    },
    {
      title: 'Data Analyst Intern',
      company: 'Univac',
      year: '2019',
      desc: [
        `Built Python ETL pipelines \n Streamed shop floor metrics via Kafka and NodeJS to surface near real-time insights`,
      ],
    },
    {
      title: 'Diploma In Mechanical Engineering',
      company: 'Singapore Polytechnic',
      year: '2015',
      desc: 'Graduated with a Diploma With Merit',
    },
  ],
}
